### PR TITLE
Cookie Clicker

### PR DESCRIPTION
**Pull request by A12509188**
Added Cookie Clicker files, and edited emupedia.net/beta/index.html, and added the Cookie Clicker link

### CODE REVIEW

**Comment by A12509188** [comment]
All that is left to do is update emupedia.net/beta/emuos/index.html, so that the Cookie Clicker iframe goes to emupedia.net/beta/emuos/vfat/games/cookie-clicker/index.html

**Comment by A12509188** [comment]
Is anybody going to merge my pull request?

**Comment by ZaDarkSide** [comment]
I'm still reviewing it.

**Comment by ZaDarkSide** [comment]
I think we need permission from the author(s) to include this code in the repo. This is the only problem.

**Comment by A12509188** [comment]
ozh.github.io, it isn't even his, he just copied the files from the author at http://orteil.dashnet.org/cookieclicker/

**Comment by A12509188** [comment]
It's not open source, it's copyrighted, but anyways there's a bunch of copyrighted games in your site. I don't think this counts as "preservation".

**Comment by A12509188** [comment]
Can't you just email him for permission?

**Comment by ZaDarkSide** [comment]
I will try, I have joined their official Discord server: https://discordapp.com/invite/cookie

**Comment by A12509188** [comment]
The link to Cookie Clicker doesn't work, because Emupedia is https, but orteil.dashnet.org/cookieclicker/ is http

**Comment by A12509188** [comment]
The JS console gives this error: "The page at 'https://emupedia.net/beta/emuos/' was loaded over HTTPS, but requested an insecure resource 'http://orteil.dashnet/cookieclicker/'. This request has been blocked; the content must be served over HTTPS."

**Comment by ZaDarkSide** [comment]
I'm working on a fix, if you want to discuss more, join our Discord: https://discord.gg/wXtGQ4p
Discussing things in a pull request is not very efficient.

**Pull request merged**
